name: CI checks for repo

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-format:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Frontend checks(build,lint,format)
          run: npm ci
          working-directory: Athlead-client

        - run: npm run format:check
          working-directory: Athlead-client

        - run: npm run lint
          working-directory: Athlead-client

        - run: npm run build
          working-directory: Athlead-client

        # BACKEND

        - name: Backend Checks checks(build,lint,format)
          run: npm ci
          working-directory: Backend

        - run: npm run format:check
          working-directory: Backend

        - run: npm run lint
          working-directory: Backend